[workspace]
members = [ "crates/block_io", "crates/lru", "crates/mutex_api", "crates/once_init", "crates/page_alloc", "crates/xv6_fs_types", "crates/xv6_kernel_params", "crates/xv6_syscall", "crates/xv6_user_lib", "crates/xv6_user_syscall", "kernel" , "mkfs", "user"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
bitflags = "2.8.0"
dataview = "1.0.1"
riscv = "0.12.1"

block_io = { path = "crates/block_io" }
lru = { path = "crates/lru" }
mutex_api = { path = "crates/mutex_api" }
once_init = { path = "crates/once_init" }
page_alloc = { path = "crates/page_alloc" }
strum = { version = "0.27.1", default-features = false, features = ["derive"] }
xv6_fs_types = { path = "crates/xv6_fs_types" }
xv6_kernel_params = { path = "crates/xv6_kernel_params" }
xv6_syscall = { path = "crates/xv6_syscall" }
xv6_user_lib = { path = "crates/xv6_user_lib" }
xv6_user_syscall = { path = "crates/xv6_user_syscall" }

[profile.release]
debug = "full"
