[workspace]
members = [
    "crates/block_io",
    "crates/lru",
    "crates/mutex_api",
    "crates/once_init",
    "crates/ov6_fs_types",
    "crates/ov6_kernel_params",
    "crates/ov6_syscall",
    "crates/ov6_user_lib",
    "crates/page_alloc",
    "crates/slab_allocator",
    "kernel",
    "mkfs",
    "user"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
arrayvec = { version = "0.7.6", default-features = false }
bitflags = "2.9.0"
dataview = "1.0.1"
memchr = { version = "2.7.4", default-features = false, features = ["alloc"] }
riscv = "0.12.1"
strum = { version = "0.27.1", default-features = false, features = ["derive"] }
thiserror = { version = "2.0.12", default-features = false }

block_io = { path = "crates/block_io" }
lru = { path = "crates/lru" }
mutex_api = { path = "crates/mutex_api" }
once_init = { path = "crates/once_init" }
ov6_fs_types = { path = "crates/ov6_fs_types" }
ov6_kernel_params = { path = "crates/ov6_kernel_params" }
ov6_syscall = { path = "crates/ov6_syscall" }
ov6_user_lib = { path = "crates/ov6_user_lib" }
page_alloc = { path = "crates/page_alloc" }
slab_allocator = { path = "crates/slab_allocator" }

[profile.release]
debug = "full"
panic = "abort"
lto = "fat"

[profile.dev]
debug = "full"
panic = "abort"

[profile.initcode]
inherits = "release"
debug = "full"
lto = "fat"
