[workspace]
members = [ "crates/block_io", "crates/lru", "crates/mutex_api", "crates/once_init", "crates/page_alloc", "crates/slab_allocator", "crates/xv6_fs_types", "crates/xv6_kernel_params", "crates/xv6_syscall", "crates/xv6_user_lib", "kernel" , "mkfs", "user"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
arrayvec = { version = "0.7.6", default-features = false }
bitflags = "2.8.0"
dataview = "1.0.1"
memchr = { version = "2.7.4", default-features = false, features = ["alloc"] }
riscv = "0.12.1"

block_io = { path = "crates/block_io" }
lru = { path = "crates/lru" }
mutex_api = { path = "crates/mutex_api" }
once_init = { path = "crates/once_init" }
page_alloc = { path = "crates/page_alloc" }
slab_allocator = { path = "crates/slab_allocator" }
strum = { version = "0.27.1", default-features = false, features = ["derive"] }
thiserror = { version = "2.0.11", default-features = false }
xv6_fs_types = { path = "crates/xv6_fs_types" }
xv6_kernel_params = { path = "crates/xv6_kernel_params" }
xv6_syscall = { path = "crates/xv6_syscall" }
xv6_user_lib = { path = "crates/xv6_user_lib" }

[profile.release]
debug = "full"
panic = "abort"

[profile.dev]
debug = "full"
panic = "abort"
