[package]
name = "user"
version.workspace = true
edition.workspace = true

[dependencies]
ov6_fs_types.workspace = true
ov6_kernel_params.workspace = true
ov6_user_lib.workspace = true

[dev-dependencies]
ov6_user_lib = {workspace = true, features = ["std"]}
